#! /usr/bin/python

from typing import Final, List
import subprocess
import os


def load_args() -> List[str]:
    result: Final[str]
    with open("compile_flags.txt", "r") as f:
        result = f.read()
    return result.split()


if not os.path.exists("build"):
    os.mkdir("build")

subprocess.run([ "gcc", *load_args(), "src/_btrstd.c", "-c", "-o", "build/btrstd.a" ])
