#! /usr/bin/env python3

from typing import Final, List, Tuple, Optional
from enum import StrEnum
import subprocess
import argparse
import shutil
import time
import os


BUILD_ARGS_FILE: Final[str] = "compile_flags.txt"
TESTS_DIR      : Final[str] = "tests"
BUILD_DIR      : Final[str] = "build"
OBJ_FILE       : Final[str] = "_btrstd.o"
LIB_FILE       : Final[str] = "libbtrstd.a"
COMPILE_THIS   : Final[str] = os.path.join("src", "_btrstd.c")
TESTS_BUILD_DIR: Final[str] = os.path.join(BUILD_DIR, "tests")


class Commands(StrEnum):
    BUILD = "build"
    CLEAN = "clean"
    TEST  = "test"


def load_args() -> List[str]:
    with open(BUILD_ARGS_FILE, "r") as f:
        result: Final[str] = f.read()
    return result.split()


def task_build() -> None:

    if shutil.which("gcc") is None:
        print("GCC not found")
        return
    if shutil.which("ar") is None:
        print("ar not found")
        return
    if not os.path.exists(BUILD_DIR):
        os.mkdir(BUILD_DIR)
    res: subprocess.CompletedProcess[bytes] = subprocess.run([
        "gcc",
        *load_args(),
        "-c",
        COMPILE_THIS,
        "-o",
        os.path.join(BUILD_DIR, OBJ_FILE)
    ])
    if res.returncode != 0:
        print(f"Build failed with return code of {res.returncode}")
        return
    res = subprocess.run([
        "ar", "rcs",
        os.path.join(BUILD_DIR, LIB_FILE),
        os.path.join(BUILD_DIR, OBJ_FILE)
    ])
    if res.returncode == 0:
        print("Build successfull")
    else:
        print(f"Archiving failed with return code of {res.returncode}")
        return

def task_test(test: Optional[str], performance: bool) -> None:

    def perform_test(file: str) -> None:

        def launch_test(test_name: str) -> Tuple[float, subprocess.CompletedProcess[bytes]]:
            start: float = time.perf_counter()
            testResult: subprocess.CompletedProcess[bytes] = subprocess.run([
                os.path.join("build", test_name)
            ])
            return time.perf_counter() - start, testResult

        test_name: str = os.path.basename(file).split(".")[0]
        buildResult: subprocess.CompletedProcess[bytes] = subprocess.run([
            "gcc",
            *build_args,
            "-fsanitize=address",
            os.path.join(TESTS_DIR, file),
            "-Lbuild",
            "-lbtrstd",
            "-o",
            os.path.join("build", test_name)
        ])
        if buildResult.returncode != 0:
            print(f"Build of {os.path.basename(file)} failed with return code of {buildResult.returncode}")
            return
        print(f">>> Testing {os.path.basename(file)}")
        if performance:
            elapseds: List[float] = []
            for _ in range(100):
                just_elapsed, testResult = launch_test(test_name)
                if testResult.returncode != 0:
                    print(f"Test {os.path.basename(file)} failed with return code of {buildResult.returncode}")
                    return
                elapseds.append(just_elapsed)
            print(f"Test {os.path.basename(file)} passed in {sum(elapseds) / len(elapseds):.3f}s on average and in {sum(elapseds):.3f} in total")
        else:
            elapsed, testResult = launch_test(test_name)
            if testResult.returncode == 0:
                print(f"Test {os.path.basename(file)} passed in {elapsed:.3f}s")
            else:
                print(f"Test {os.path.basename(file)} failed with return code of {buildResult.returncode}")

    task_build()

    if not os.path.exists(TESTS_BUILD_DIR):
        os.mkdir(TESTS_BUILD_DIR)

    build_args: Final[List[str]] = load_args()
    if test:
        perform_test(test + ".c")
        return
    for test in os.listdir(TESTS_DIR):
        perform_test(test)

def task_clean() -> None:

    if os.path.exists(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)


if __name__ == "__main__":

    parser: Final[argparse.ArgumentParser] = argparse.ArgumentParser(
        prog="buildSystem",
        description="BetterSTD build system"
    )
    subparsers: argparse._SubParsersAction[argparse.ArgumentParser] = \
        parser.add_subparsers(dest="action", required=True)

    test_parser: argparse.ArgumentParser = subparsers.add_parser("test")
    test_parser.add_argument("test_name", nargs="?")
    test_parser.add_argument("--list", action="store_true")
    test_parser.add_argument("--performance", action="store_true")

    subparsers.add_parser("build")
    subparsers.add_parser("clean")

    args: argparse.Namespace = parser.parse_args()

    if args.action == "build":
        task_build()
    elif args.action == "test":
        if args.list:
            print("Available tests:")
            for test in os.listdir(TESTS_DIR):
                print("    " + test.split(".")[0])
            if not args.test_name:
                exit()
        task_test(args.test_name, args.performance)
    elif args.action == "clean":
        task_clean()

